generation_config:
    temperature: 1.0
    top_p: 0.9
    top_k: 50
    num_beams: 1
    use_cache: True
    repetition_penalty: 1.2
    max_new_tokens: 512
    do_sample: True
    eos_token_id: 1
    pad_token_id: 0
